### ISSUE TITLE
Реализовать изменение роли юзера

### ISSUE THREAD

**Issue by Trunker2010** [rjhdby/motoDtpBackend#23]
Поменял в БД роль с USER на MODERATOR в ответе GET ​/v1​/user​/ все равно приходит USER.

**Comment by rjhdby** [comment]
Пользователь берётся из кеша. Если ты руками в базе поменял, то надо либо рестартануть бэк, либо дождаться инвалидации (4 часа).
Добавлю, пожалуй, ручку для ручной инвалидации

**Comment by rjhdby** [comment]
Сделал ручку /invalidate/{userId}

**Comment by elagin** [comment]
Жесть какая-то. Ручками ни кто не должен в базе ни чего делать. Зачем костыль было еще и в API вытаскивать?
