### ISSUE TITLE
Не работает авторизация ВК

### ISSUE THREAD

**Issue by Trunker2010** [rjhdby/motoDtpBackend#28]
При переходе по: https://oauth.vk.com/authorize?client_id=6355438&display=mobile&redirect_uri=http://188.166.126.84:8080/v1/user/register/vk&response_type=code&v=5.130 получаем ошибку.

**Comment by elagin** [comment]
Какую ошибку? Где пример?

**Comment by elagin** [comment]
`<html><body><h1>Whitelabel Error Page</h1><p>This application has no configured error view, so you are seeing this as a fallback.</p><div id='created'>Tue Jun 01 21:31:38 GMT 2021</div><div>[8e50b976-2] There was an unexpected error (type=Internal Server Error, status=500).</div><div></div></body></html>`

**Comment by rjhdby** [comment]
Вернул на http, теперь должно работать по идее

**Comment by Trunker2010** [comment]
Все так же

**Comment by Trunker2010** [comment]
Как я понял, авторизация работает не везде, на моем устройстве не загружается, на другом загружается, в одном браузере загружается, в другом нет. Где не загружается, отображается ошибка, которая была указана выше.

**Comment by Trunker2010** [comment]
Разобрался. Похожее у меня приложение устанавливалось со старым кэшем, то же самое было в браузере. После сброса заработало.

**Comment by Trunker2010** [comment]
Теперь после ввода данных для авторизации, вместо токена получаем ту же самую ошибку.
